# Generated by Django 3.2 on 2023-10-19 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=256, verbose_name='Text ID of data')),
                ('source_name', models.CharField(blank=True, default='', max_length=32)),
                ('param1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Custom Parameter 1')),
                ('param2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Custom Parameter 2')),
                ('data', models.TextField(blank=True, default='')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagramFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of diagram', max_length=256)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('diagram_type', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.FileField(help_text='JSON file with list of objects', max_length=300, upload_to='iframe-diagrams/')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('updated_user_name', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
