# Generated by Django 4.2 on 2023-10-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagramframe',
            name='updated_user_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
