# Generated by Django 4.2 on 2024-07-12 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagrams', '0004_add_missing_chart_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view_platform', 'View Platform')], default='view_platform', help_text='Access level', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Request status', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who has requested access', on_delete=django.db.models.deletion.CASCADE, related_name='platform_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Access',
                'verbose_name_plural': 'Platform Access',
            },
        ),
    ]
