# Generated by Django 4.2 on 2024-07-17 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagrams', '0005_platformaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedDashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_url', models.CharField(max_length=500)),
                ('domain', models.CharField(max_length=500)),
                ('diagram_slug', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default={})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('diagram_instance', models.ForeignKey(help_text='Diagram instance', on_delete=django.db.models.deletion.CASCADE, related_name='deployed_diagrams', to='diagrams.diagramframe')),
                ('user', models.ForeignKey(help_text='User who has deployed dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='deployed_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deployed Dashboard',
                'verbose_name_plural': 'Deployed Dashboards',
                'ordering': ['-created'],
            },
        ),
    ]
