# Generated by Django 4.2 on 2024-08-15 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagrams', '0007_alter_deployeddashboards_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', help_text='Path of old json file', max_length=600, null=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Changes made to diagram', null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='Date and time when log was created', null=True)),
                ('diagram', models.ForeignKey(help_text='Diagram to which this log belongs', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='diagrams.diagramframe')),
                ('user', models.ForeignKey(help_text='User who made changes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagram_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagram Log',
                'verbose_name_plural': 'Diagram Logs',
                'ordering': ['-dt_created'],
            },
        ),
    ]
