# Generated by Django 4.2 on 2024-08-16 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagrams', '0008_diagramlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagramframe',
            name='accessible_by',
            field=models.ManyToManyField(blank=True, help_text='Restrict access to diagram to specific users, empty means everyone can access', related_name='accessible_diagrams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagramframe',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='If true, the entire diagram is protected with a password and Email/password authentication'),
        ),
        migrations.AddField(
            model_name='diagramframe',
            name='passkey',
            field=models.CharField(blank=True, default='', help_text='Password to access diagram', max_length=256, null=True),
        ),
    ]
