# Generated by Django 4.2 on 2024-09-16 06:40

import diagrams.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagrams', '0009_diagramframe_accessible_by_diagramframe_is_protected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ITToolProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Unique title for the tool', max_length=256, unique=True)),
                ('image', models.ImageField(help_text='Image representing the tool', upload_to=diagrams.models.upload_image_to)),
                ('description', models.TextField(blank=True, help_text='Description of the tool', null=True)),
                ('demo_link', models.URLField(blank=True, help_text='Link to the demo of the tool', null=True)),
                ('create_link', models.URLField(help_text='Link to create/access the tool')),
                ('file_example', models.FileField(blank=True, help_text='Example file for the tool', null=True, upload_to=diagrams.models.upload_file_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category the tool belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='diagrams.category')),
                ('user', models.ForeignKey(blank=True, help_text='User who created the tool', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ittool_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ittool Product',
                'verbose_name_plural': 'Ittool Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
