const originalData = {
  name: 'COVID-19 Municipal Pandemic Response: Top 50 Cities',
  data: [
    {
      city: 'Abu Dhabi',
      'Goverment Efficiency': 59.87,
      'Economic Resilience': 49.57,
      'Quarantine Management': 80.37,
      'Healthcare Management': 65.39,
      'Vaccination Rate': 87.21,
      'Cultural Compliance': 71.71,
    },
    {
      city: 'Singapure',
      'Goverment Efficiency': 66.16,
      'Economic Resilience': 65.57,
      'Quarantine Management': 61.66,
      'Healthcare Management': 67.65,
      'Vaccination Rate': 77.24,
      'Cultural Compliance': 69.41,
    },
    {
      city: 'Seoul',
      'Goverment Efficiency': 53.2,
      'Economic Resilience': 60.98,
      'Quarantine Management': 55.67,
      'Healthcare Management': 71.27,
      'Vaccination Rate': 88.32,
      'Cultural Compliance': 67.22,
    },
    {
      city: 'Ottawa',
      'Goverment Efficiency': 58.82,
      'Economic Resilience': 61.11,
      'Quarantine Management': 70.59,
      'Healthcare Management': 62.08,
      'Vaccination Rate': 80.74,
      'Cultural Compliance': 56.31,
    },
    {
      city: 'Tokio',
      'Goverment Efficiency': 58.13,
      'Economic Resilience': 63.85,
      'Quarantine Management': 57.49,
      'Healthcare Management': 66.4,
      'Vaccination Rate': 81.28,
      'Cultural Compliance': 60.35,
    },
    {
      city: 'Zurich',
      'Goverment Efficiency': 61.75,
      'Economic Resilience': 63.87,
      'Quarantine Management': 43.12,
      'Healthcare Management': 70.47,
      'Vaccination Rate': 81.78,
      'Cultural Compliance': 63.51,
    },
    {
      city: 'Amsterdam',
      'Goverment Efficiency': 65.75,
      'Economic Resilience': 59.9,
      'Quarantine Management': 54.77,
      'Healthcare Management': 65.47,
      'Vaccination Rate': 75.3,
      'Cultural Compliance': 61.23,
    },
    {
      city: 'Beijing',
      'Goverment Efficiency': 59.67,
      'Economic Resilience': 52.22,
      'Quarantine Management': 74.79,
      'Healthcare Management': 65.93,
      'Vaccination Rate': 65.62,
      'Cultural Compliance': 62.52,
    },
    {
      city: 'Toronto',
      'Goverment Efficiency': 57.86,
      'Economic Resilience': 60.47,
      'Quarantine Management': 63.2,
      'Healthcare Management': 66.26,
      'Vaccination Rate': 75.18,
      'Cultural Compliance': 55.45,
    },
    {
      city: 'Oslo',
      'Goverment Efficiency': 58.81,
      'Economic Resilience': 56.98,
      'Quarantine Management': 70.82,
      'Healthcare Management': 62.71,
      'Vaccination Rate': 71.3,
      'Cultural Compliance': 57.66,
    },
    {
      city: 'Auckland',
      'Goverment Efficiency': 67.16,
      'Economic Resilience': 62.67,
      'Quarantine Management': 61.49,
      'Healthcare Management': 67.52,
      'Vaccination Rate': 56.8,
      'Cultural Compliance': 61.75,
    },
    {
      city: 'Canberra',
      'Goverment Efficiency': 57.44,
      'Economic Resilience': 57.04,
      'Quarantine Management': 65.28,
      'Healthcare Management': 65.14,
      'Vaccination Rate': 78.67,
      'Cultural Compliance': 51.56,
    },
    {
      city: 'Almaty',
      'Goverment Efficiency': 53.35,
      'Economic Resilience': 49.44,
      'Quarantine Management': 79.55,
      'Healthcare Management': 63.85,
      'Vaccination Rate': 61.35,
      'Cultural Compliance': 66.35,
    },
    {
      city: 'New York',
      'Goverment Efficiency': 43.61,
      'Economic Resilience': 63.67,
      'Quarantine Management': 62.22,
      'Healthcare Management': 62.4,
      'Vaccination Rate': 86.18,
      'Cultural Compliance': 52.4,
    },
    {
      city: 'Dubai',
      'Goverment Efficiency': 51.05,
      'Economic Resilience': 44.08,
      'Quarantine Management': 63.07,
      'Healthcare Management': 63.22,
      'Vaccination Rate': 79.08,
      'Cultural Compliance': 72.63,
    },
    {
      city: 'Sydney',
      'Goverment Efficiency': 57.91,
      'Economic Resilience': 53.32,
      'Quarantine Management': 67.74,
      'Healthcare Management': 64.92,
      'Vaccination Rate': 77.34,
      'Cultural Compliance': 51.54,
    },
    {
      city: 'Manama',
      'Goverment Efficiency': 62.34,
      'Economic Resilience': 59.48,
      'Quarantine Management': 66.39,
      'Healthcare Management': 58.83,
      'Vaccination Rate': 61.38,
      'Cultural Compliance': 63.49,
    },
    {
      city: 'Berlin',
      'Goverment Efficiency': 53.37,
      'Economic Resilience': 67.49,
      'Quarantine Management': 55.23,
      'Healthcare Management': 66.08,
      'Vaccination Rate': 65.99,
      'Cultural Compliance': 63.73,
    },
    {
      city: 'Los Angeles',
      'Goverment Efficiency': 48.86,
      'Economic Resilience': 63.26,
      'Quarantine Management': 63.82,
      'Healthcare Management': 59.98,
      'Vaccination Rate': 83.44,
      'Cultural Compliance': 52.12,
    },
    {
      city: 'Shanhai',
      'Goverment Efficiency': 55.74,
      'Economic Resilience': 52.43,
      'Quarantine Management': 66.34,
      'Healthcare Management': 64.69,
      'Vaccination Rate': 66.13,
      'Cultural Compliance': 62.52,
    },
    {
      city: 'Kuala Lumpur',
      'Goverment Efficiency': 53.57,
      'Economic Resilience': 50.64,
      'Quarantine Management': 67.49,
      'Healthcare Management': 61.56,
      'Vaccination Rate': 71.76,
      'Cultural Compliance': 60.9,
    },
    {
      city: 'Riyadh',
      'Goverment Efficiency': 58.27,
      'Economic Resilience': 48.21,
      'Quarantine Management': 76.49,
      'Healthcare Management': 60.79,
      'Vaccination Rate': 58.61,
      'Cultural Compliance': 61.51,
    },
    {
      city: 'London',
      'Goverment Efficiency': 55.01,
      'Economic Resilience': 56.25,
      'Quarantine Management': 49.3,
      'Healthcare Management': 65.54,
      'Vaccination Rate': 82.96,
      'Cultural Compliance': 52.39,
    },
    {
      city: 'Wellington',
      'Goverment Efficiency': 57.6,
      'Economic Resilience': 59.77,
      'Quarantine Management': 63.84,
      'Healthcare Management': 62.38,
      'Vaccination Rate': 59.83,
      'Cultural Compliance': 57.66,
    },
    {
      city: 'Dublin',
      'Goverment Efficiency': 52.69,
      'Economic Resilience': 59.08,
      'Quarantine Management': 52.39,
      'Healthcare Management': 63.23,
      'Vaccination Rate': 79.59,
      'Cultural Compliance': 52.13,
    },
    {
      city: 'Bern',
      'Goverment Efficiency': 58.95,
      'Economic Resilience': 60.77,
      'Quarantine Management': 44.38,
      'Healthcare Management': 73.54,
      'Vaccination Rate': 56.71,
      'Cultural Compliance': 63.51,
    },
    {
      city: 'Jakarta',
      'Goverment Efficiency': 57.31,
      'Economic Resilience': 51.03,
      'Quarantine Management': 64.87,
      'Healthcare Management': 54.91,
      'Vaccination Rate': 63.6,
      'Cultural Compliance': 65.87,
    },
    {
      city: 'Paris',
      'Goverment Efficiency': 57.14,
      'Economic Resilience': 55.28,
      'Quarantine Management': 50.08,
      'Healthcare Management': 63.3,
      'Vaccination Rate': 66.17,
      'Cultural Compliance': 64.89,
    },
    {
      city: 'Madrid',
      'Goverment Efficiency': 54.92,
      'Economic Resilience': 50.78,
      'Quarantine Management': 66.33,
      'Healthcare Management': 63.97,
      'Vaccination Rate': 57.78,
      'Cultural Compliance': 62.71,
    },
    {
      city: 'Doha',
      'Goverment Efficiency': 60.49,
      'Economic Resilience': 50.1,
      'Quarantine Management': 67.32,
      'Healthcare Management': 50.23,
      'Vaccination Rate': 59.16,
      'Cultural Compliance': 68.15,
    },
    {
      city: 'Copenhagen',
      'Goverment Efficiency': 62.68,
      'Economic Resilience': 60.21,
      'Quarantine Management': 53.89,
      'Healthcare Management': 62.62,
      'Vaccination Rate': 57.04,
      'Cultural Compliance': 56.27,
    },
    {
      city: 'Helsinki',
      'Goverment Efficiency': 59.67,
      'Economic Resilience': 60.37,
      'Quarantine Management': 50.74,
      'Healthcare Management': 67.9,
      'Vaccination Rate': 53.29,
      'Cultural Compliance': 60.36,
    },
    {
      city: 'Barcelona',
      'Goverment Efficiency': 56.25,
      'Economic Resilience': 55.31,
      'Quarantine Management': 61.86,
      'Healthcare Management': 61.42,
      'Vaccination Rate': 54.13,
      'Cultural Compliance': 62.71,
    },
    {
      city: 'Brussels',
      'Goverment Efficiency': 55.63,
      'Economic Resilience': 54.96,
      'Quarantine Management': 53.39,
      'Healthcare Management': 61.97,
      'Vaccination Rate': 62.27,
      'Cultural Compliance': 57.36,
    },
    {
      city: 'Tel Aviv',
      'Goverment Efficiency': 49.82,
      'Economic Resilience': 57.57,
      'Quarantine Management': 51.19,
      'Healthcare Management': 62.15,
      'Vaccination Rate': 68.23,
      'Cultural Compliance': 56.41,
    },
    {
      city: 'Kuwait City',
      'Goverment Efficiency': 50.87,
      'Economic Resilience': 47.31,
      'Quarantine Management': 71.85,
      'Healthcare Management': 52.26,
      'Vaccination Rate': 53.29,
      'Cultural Compliance': 67.82,
    },
    {
      city: 'Stockholm',
      'Goverment Efficiency': 51.2,
      'Economic Resilience': 56.5,
      'Quarantine Management': 61.65,
      'Healthcare Management': 63.42,
      'Vaccination Rate': 52.3,
      'Cultural Compliance': 57.93,
    },
    {
      city: 'Sao Paulo',
      'Goverment Efficiency': 60.22,
      'Economic Resilience': 44.18,
      'Quarantine Management': 65.48,
      'Healthcare Management': 57.1,
      'Vaccination Rate': 62.76,
      'Cultural Compliance': 51.67,
    },
    {
      city: 'Manila',
      'Goverment Efficiency': 45.02,
      'Economic Resilience': 41.7,
      'Quarantine Management': 75.11,
      'Healthcare Management': 55.64,
      'Vaccination Rate': 62.54,
      'Cultural Compliance': 60.97,
    },
    {
      city: 'New Delhi',
      'Goverment Efficiency': 48.17,
      'Economic Resilience': 38.23,
      'Quarantine Management': 63.39,
      'Healthcare Management': 63.02,
      'Vaccination Rate': 64.62,
      'Cultural Compliance': 62.57,
    },
    {
      city: 'Rome',
      'Goverment Efficiency': 45.55,
      'Economic Resilience': 52.36,
      'Quarantine Management': 51.26,
      'Healthcare Management': 55.5,
      'Vaccination Rate': 73.87,
      'Cultural Compliance': 58.58,
    },
    {
      city: 'Santiago',
      'Goverment Efficiency': 55.11,
      'Economic Resilience': 51.86,
      'Quarantine Management': 54.65,
      'Healthcare Management': 57.09,
      'Vaccination Rate': 56.85,
      'Cultural Compliance': 60.53,
    },
    {
      city: 'Taipei',
      'Goverment Efficiency': 54.3,
      'Economic Resilience': 49.4,
      'Quarantine Management': 44.86,
      'Healthcare Management': 61.49,
      'Vaccination Rate': 51.41,
      'Cultural Compliance': 73.84,
    },
    {
      city: 'Lisbon',
      'Goverment Efficiency': 58.86,
      'Economic Resilience': 45.16,
      'Quarantine Management': 59.07,
      'Healthcare Management': 54.69,
      'Vaccination Rate': 53.49,
      'Cultural Compliance': 63.66,
    },
    {
      city: 'Vienna',
      'Goverment Efficiency': 50.76,
      'Economic Resilience': 56.89,
      'Quarantine Management': 50.87,
      'Healthcare Management': 66.19,
      'Vaccination Rate': 53.82,
      'Cultural Compliance': 54.21,
    },
    {
      city: 'Hong Kong',
      'Goverment Efficiency': 53.38,
      'Economic Resilience': 46.6,
      'Quarantine Management': 56.41,
      'Healthcare Management': 57.44,
      'Vaccination Rate': 55.63,
      'Cultural Compliance': 61.49,
    },
    {
      city: 'Lima',
      'Goverment Efficiency': 49.21,
      'Economic Resilience': 46.65,
      'Quarantine Management': 73.73,
      'Healthcare Management': 42.49,
      'Vaccination Rate': 60.87,
      'Cultural Compliance': 57.17,
    },
    {
      city: 'Tallinn',
      'Goverment Efficiency': 51.31,
      'Economic Resilience': 60.79,
      'Quarantine Management': 52.1,
      'Healthcare Management': 62.48,
      'Vaccination Rate': 37.3,
      'Cultural Compliance': 62.94,
    },
    {
      city: 'Hanoi',
      'Goverment Efficiency': 45.3,
      'Economic Resilience': 44.62,
      'Quarantine Management': 54.48,
      'Healthcare Management': 61.82,
      'Vaccination Rate': 60.48,
      'Cultural Compliance': 59,
    },
    {
      city: 'Vilnius',
      'Goverment Efficiency': 43.56,
      'Economic Resilience': 58.93,
      'Quarantine Management': 56.06,
      'Healthcare Management': 59.11,
      'Vaccination Rate': 53.17,
      'Cultural Compliance': 54.7,
    },
  ],
};
