import {  
  NEW_GENERATION_BUSINESS_DEVELOPMENT_SECTIONS,
  STRATEGIC_ENGAGEMENT_PLAN,
  BIZDEV_PERFOMANCE_REPORT,
  BIZDEV_PERFOMANCE_DASHBOARD,
  LEADS_SECTIONS,
  BIZDEV_PROSPECT_ANALYSIS,
  LEAD_GENERATION_PIPELINE,
  TIER_PLATFORM,
  TIER_PLATFORM_DEEP_INNOVATION,
  TIER_PLATFORM_ECOSYSTEM_MAP,
  TIER_PLATFORM_2,
  TIER_PLATFORM_3,
  BIZDEV_TECH_EMAIL_CONSTRUCTOR,
  SALES_MESSAGING_CONSTRUCTOR,
  SMM_PROMOTION_CONSTRUCTOR,
  SAAS_SALES_READY_PROJECTS,
  DASHBOARDS_SALES_READY_PROJECTS,
  SERVICES_SALES_READY_PROJECTS,
  DISTRIBUTOR_PARTNERSHIPS_PLATFORM_SAAS,
  DISTRIBUTOR_PARTNERSHIPS_PLATFORM_DASHBOARDS,
  REPRESENTATIVES_PARTNERSHIPS_PLATFORM,
  ERMS30,
  DASHBOARD_USER_JOURNEY,
  SAAS_USER_JOURNEY,
  BIZDEV_CONSTRUCTOR,
  READYPROJECTS,
  PARTNERSHIPSPLATFORMS,
  USERJOURNEYS,
} from "./diagram";

export const BUSINESS_DEVELOPMENT_SECTIONS = {
  [NEW_GENERATION_BUSINESS_DEVELOPMENT_SECTIONS]: [
    STRATEGIC_ENGAGEMENT_PLAN,
    BIZDEV_PERFOMANCE_REPORT,
    BIZDEV_PERFOMANCE_DASHBOARD
  ],
  [LEADS_SECTIONS]: [
    BIZDEV_PROSPECT_ANALYSIS,
    LEAD_GENERATION_PIPELINE,
  ],
  [TIER_PLATFORM] : [
    TIER_PLATFORM_DEEP_INNOVATION,
    TIER_PLATFORM_ECOSYSTEM_MAP,
    TIER_PLATFORM_2,
    TIER_PLATFORM_3,
  ],
  [BIZDEV_CONSTRUCTOR] : [
    BIZDEV_TECH_EMAIL_CONSTRUCTOR,
    SALES_MESSAGING_CONSTRUCTOR,
    SMM_PROMOTION_CONSTRUCTOR,
  ],
  [READYPROJECTS] : [
    SAAS_SALES_READY_PROJECTS,
    DASHBOARDS_SALES_READY_PROJECTS,
    SERVICES_SALES_READY_PROJECTS,
  ],
  [PARTNERSHIPSPLATFORMS] : [
    DISTRIBUTOR_PARTNERSHIPS_PLATFORM_SAAS,
    DISTRIBUTOR_PARTNERSHIPS_PLATFORM_DASHBOARDS,
    REPRESENTATIVES_PARTNERSHIPS_PLATFORM,
  ],
  [ERMS30] : [
    ERMS30,
  ],
  [USERJOURNEYS] : [
    DASHBOARD_USER_JOURNEY,
    SAAS_USER_JOURNEY,
  ],
};
