import {
  AI_ECONOMY_BIOMED,
  AI_ECONOMY_UK,
  AI_ECONOMY_US,
  AI_ECO_SIZE_ASSESMENT,
  AI_PHARMA_INVEST_DIGEST,
  AI_PHARMA_INVEST_DIGEST_DASH_2,
  AI_PHARMA_INVEST_DIGEST_DASH_3,
  BIG_DATA_SYS_DASH2,
  BIG_DATA_SYS_DASH3,
  BTQ_DASH2,
  BTQ_DASH3,
  DATA_MANAGEMENT,
  DATA_MANAGEMENT_PROG__DEC_2023,
  DATA_VISUALISATION,
  DATA_VISUALISATION_PROG_DEC_2023,
  DEEP_PHARMA_INTEL_DASH2,
  DEEP_PHARMA_INTEL_DASH3,
  FEMTECH_DASH2,
  FEMTECH_DASH3,
  GLOBAL_AI_ECONOMY,
  INVESTECH_PLAT_DASH2,
  INVESTECH_PLAT_DASH3,
  IR5TH_PROJECT,
  LONGEVITY_MHEALTH_DASH2,
  LONGEVITY_MHEALTH_DASH3,
  OE_SMS_DASH2,
  OE_SMS_DASH3,
  OFF_WORLD_DASH2,
  OFF_WORLD_DASH3,
  PARSING_TEAM,
  PROGRESS_SUMMARY,
  QUANTUM_COMPUTING_FRAME,
  TECHNO_PROG,
  TECH_ECO_FIN_DEPT,
  TECH_ECO_FIN_PROG,
  TECH_FIN_PLAT_DASH2,
  TECH_FIN_PLAT_DASH3,
  VALOUR_DASH2,
  VALOUR_DASH3,
} from "./diagram";

export const TECH_ECO_FIN_SECTION = {
  [TECH_ECO_FIN_DEPT]: [TECH_ECO_FIN_PROG],
  [AI_PHARMA_INVEST_DIGEST]: [
    AI_PHARMA_INVEST_DIGEST_DASH_2,
    AI_PHARMA_INVEST_DIGEST_DASH_3,
  ],
  [AI_ECO_SIZE_ASSESMENT]: [
    GLOBAL_AI_ECONOMY,
    AI_ECONOMY_UK,
    AI_ECONOMY_US,
    AI_ECONOMY_BIOMED,
  ],
};

export const DATA_MANAGEMENT_SECTION = {
  [DATA_MANAGEMENT]: [DATA_MANAGEMENT_PROG__DEC_2023],
};

export const DATA_VISUALISATION_SECTION = {
  [DATA_VISUALISATION]: [DATA_VISUALISATION_PROG_DEC_2023],
};

export const PARSING_TEAM_SECTION = {
  [PARSING_TEAM]: [PROGRESS_SUMMARY],
};

export const ALGORITHMIC_SECTION = {
  [IR5TH_PROJECT]: [QUANTUM_COMPUTING_FRAME, TECHNO_PROG],
  [OE_SMS_DASH2]: [
    BIG_DATA_SYS_DASH2,
    DEEP_PHARMA_INTEL_DASH2,
    INVESTECH_PLAT_DASH2,
    LONGEVITY_MHEALTH_DASH2,
    TECH_FIN_PLAT_DASH2,
    OFF_WORLD_DASH2,
    BTQ_DASH2,
    VALOUR_DASH2,
    FEMTECH_DASH2,
  ],
  [OE_SMS_DASH3]: [
    BIG_DATA_SYS_DASH3,
    DEEP_PHARMA_INTEL_DASH3,
    INVESTECH_PLAT_DASH3,
    LONGEVITY_MHEALTH_DASH3,
    TECH_FIN_PLAT_DASH3,
    OFF_WORLD_DASH3,
    BTQ_DASH3,
    VALOUR_DASH3,
    FEMTECH_DASH3,
  ],
};
