import {
  NUM2,
  NUM3,
  NUM4,
  NUM4_5,
  NUM5,
  NUM9,
  NUM11,
  NUM14,
  NUM15,
  NUM18_1,
  UK_TUBE,
  VALINOR,
  BOOK_LIBRARY,
  NUM13,
  P3D,
  PYRAMID,
  TREE,
  RECT_MINDMAP,
  MIND_MAP,
  CUBE_3D,
  TREE_3D,
  PIE_CHART_3D,
  BAR_CHART_3D,
  CUSTOM_TABLE,
  INTERACTIVE_PANEL,
  TREE_V2,
  PYRAMID_3D,
  TABLE_WITH_BAR,
  LIST_WITH_BAR,
  MARQUEE_LIST_BAR,
  VERTICAL_BAR_DIFF,
  COMPANIES_LIST,
  COMPANIES_TABLE,
  MIND_MAPS_MENU,
  GRAPHS_MENU,
  TOOLS_MENU,
  BAR_CHARTS_SECTION,
  LISTS_SECTION,
  OTHER_SECTION,
  NODE_CHART_3D,
  GLOBE_CHART_3D,
  STACKED_BAR_CHART,
  TREE_NO_DATE,
  REVOLUTION_CUBE_3D,
  DOCUMENT_CREATOR,
  COMPARISON_SWOTS,
  MIND_MAPS_SECTION,
  FRONTEND_TOOLS_LIBRARY_MENU,
  FRONTEND_TOOLS_LIBRARY_SECTION,
  BAR_CHARTS_MENU,
  INFOGRAPHICS_MENU,
  TIME_LINE,
  NAVIGATION_ELEMENTS_MENU,
  OTHERS_MENU,
  D3D_MENU,
  DATABASE_MANAGEMENT_SYSTEM_MENU,
  IN_DEVELOPMENT_MENU,
  INFOGRAPHICS_SECTION,
  CURRENT_STATE_FEEDBACK,
  SUGGEST_FEATURE,
  PLANNED_FRONTEND_TOOLS,
  LISTS_MENU,
  IN_DEVELOPMENT_SECTION,
  NAVIGATION_MENU_SECTION,
  COMPARISON_BARS,
  HEXAGON,
  SWOT_3D,
  ADMIN_BUTTONS_MENU,
  ADMIN_BUTTONS,
  ADMIN_BUTTONS_SECTION,
  DIGITAL_UK,
  GEOMAPS_SECTION,
  GLOBAL_GEOMAP,
  GLOBAL_GEOMAP_STATS,
  USA_GEOMAP,
  EUROPE_MAP,
  TOOLS,
  DASHBOARDS_MENU,
  LINE_CHART,
  PSEUDO_PYRAMID,
  INTERACTIVE_MINDMAPS_MENU,
  INTERACTIVE_MINDMAPS_SECTION,
  CIRCLE_INTERACTIVE,
  RECTUNGULAR_INTERACTIVE,
  DOCUMENT_CREATOR_V2,
  KEY_INDICATOR,
  COMPANIES_LIST_COLOR,
  IT_PLATFROMS_REGISTRY,
  REGISTERY_FRONTEND_ALL,
  REGISTERY_FRONTEND_INDEVELOPMENT,
  REGISTERY_DASHBOARD,
  REGISTERIES_MENU,
  GAUGE_CHART,
  INTERACTIVE_PANEL_COLOR,
  INTERACTIVE_PANEL_LOGO,
  DATABOX_DASHBOARDS_MENU,
  DATABOX_DASHBOARDS_SECTION,
  AI_UK_DATABASE,
  AI_ECOSYSTEM_DATABASE,
  PHILANTRHROPY_INTERNATIONAL,
  HUBSPOT_METRICS,
  GOOGLE_ANALYTICS,
  FEMTECH_ANALYTICS_LINKEDIN,
  AIIA_SOCIAL_MEDIA_ANALYTICS,
  AIIA,
  COMPARATIVE_ANALYSIS_LINKEDIN,
  INVEST_IN_UKRAINE_TECH,
  GLOBAL_AI_ECOSYSTEM,
  DATA_ANALYTICS_PLATFORM,
  FOR_REVISION_MENU,
  FOR_REVISION_SECTION,
  FOR_REVISION,
  PENTAGON_3D,
  NUM18,
  DOCUMENT_CREATOR_SECTION,
  ORGANIZATIONS,
  PERSONALITIES,
  CUSTOM_ENTITIES,
  GENERIC_I_FRAMES,
  MINDMAPS,
  DASHBOARDS_TOOLS,
  TREES_AND_PATHWAYS,
  TREES_AND_PATHWAYS_MENU,
  MIND_MAP_REGISTRY,
  UK_MAP,
  BENCHMARK_TOOLS_MENU,
  BENCHMARK_TOOLS_SECTION,
  DECISION_TREE,
  RADIAL_TREE,
  CIRCULAR_MINDMAP_3D,
  RADAR_CHART_MENU,
  RADAR_CHART_SECTION,
  RADAR_CHART,
  SWITZERLAND_MAP,
  LONDON_MAP,
  MOLDOVA_MAP,
  MULTI_CUBE_3D,
  LONDON_MAP_STATS,
  ASIA_MAP,
  WALES_MAP,
  UAE_MAP,
  VERTICAL_BAR_FOR_MAP,
  UNIVERSAL_BAR,
  UAE_GEO_MAP_STATS,
  WALES_MAP_STATS,
  CHISINAU_MAP,
  GULF_REGION_MAP,
  UK_MAP_STATS,
  GERMANY_MAP,
  UK_MAP_NEW,
  SCOTLAND_MAP,
  MANCHESTER_MAP,
  SCOTLAND_MAP_STATS,
  SERPENTINE_PATH,
  TIMELINE_HORIZONTAL,
  MANCHESTER_MAP_STATS,
  MOLDOVA_MAP_V2,
  NORTH_IRELAND_MAP,
  NORTH_IRELAND_MAP_STATS,
  FRANCE_MAP,
  LONDON_MAP_DARK,
  LONDON_STATS_DARK,
  CANADA_MAP,
  UK_MAP_DARK,
  UK_STATS_DARK,
  CHINA_MAP_STATS,
  UK_MAP_STATIC,
  MOLDOVA_MAP_STATS,
  ISRAEL_MAP,
  JAPAN_MAP,
  CIRCULAR_INFOGRAPH_UK,
  TIME_SERIES_CHART,
  PROMO_BANNER,
  GEO_DESHBOARDS,
  GEO_DESHBOARDS_SECTION,
  GEO_DESHBOARDS_V2,
  GEO_DESHBOARDS_NO_CODE,
  TREE_MAP,
  FLOW_CHART,
  LEADER_BOARD,
  TUBE_MAP,
  FORCE_DIRECTED_TREE,
  HEAT_MAP,
  HEAT_MAP_GRID,
  FRAME_CONSTRUCTOR,
  TUBE_TREE_3D,
  PORTRAIT_IMAGE,
  UK_MAP_TOPO_LEGEND,
  DOUGHNUT_CHART,
  DEALS_STRUCTURE,
  ARROW_PROGRESS_CHART,
  NEW_GENERATION_TOOLS_SECTION,
  ORGANISATIONAL_STRUCTURE,
  BUSS_INT_DEP,
  ACCOUNTING_DEPT,
  ADMIN_TECH_DEPT,
  BIZDEVTECH_DEPT,
  DATA_SCIENCE_TECH_DEPT,
  DKG_INTERNAL_SECTION,
  DOMAINS_REGISTRY,
  GENERIC_PASSWORDS,
  IT_DEPT,
  LEGAL_TECH_DEPT,
  PHILANTHROPY_DEPT,
  LONGEVITY_GPT,
  LEGAL_EAGLE_GPT,
  IT_DEPT_GPT,
  DATA_MNGMNT_GPT,
  AI_AGENTS_SECTION,
  NEXT_GEN_SECTION,
  THE_5_IND,
  MDVS,
  DPI2_0,
  OPER_ENV_SYSTEM_SECTION,
  OPER_ENV_VAL,
  BDAS,
  DEEP_PHARMA,
  INV_TECH_PLATFORM,
  LONG_M_HEALTH,
  THECH_FIN_PLATF,
  OFF_WORLD,
  BTQ,
  VALOUR,
  MIND_MAPS_3D_SECTION,
  INTERACTIVE_3D_SECTION,
  SWOT_SECTION,
  TIME_LINE_SECTION,
  RADAR_CHART_BLURRED,
  FRAMEWORK_CONSTRUCTOR,
  MAPS_SECTION,
  TECHNO_DASHBOARD,
  GEO_DASHBOARDS_V2_MOLDOVA_EL,
  GEO_DASHBOARDS_V2_MOLDOVA_EN,
  GEO_DASHBOARDS_V2_MOLDOVA_USA,
  GEO_DASHBOARDS_V2_MOLDOVA_NC,
  HALL_OF_FAME_BANNER,
  PR_SMM_TRANSFORMER_GPT,
  INSIGHT_WRITER_GPT,
  PLATFORM_SOLUTIONS_GPT,
  ADMIN_ASSISTANT_GPT,
  LEGAL_LENS_GPT,
  BUSSINESS_INTELLIGENCE_GPT,
  AI_FINANCE_GPT,
  AI_UK_GPT,
  GEO_DASHBOARDS_V2_MOLDOVA_GENERAL,
  WEF_PANEL,
  LONGEVITY_BOOKS,
  GOVTECH_DEPT,
  PHILANTHROPY_GPT,
  GOVTECH_GPT,
  LIFE_SCIENCES_DEPT,
  D3D_SECTION,
  RECTANGLE_MINDMAP,
  INT_MINDMAP,
  AI_NEUROTECH,
  AI_HEALTHTECH,
  AI_BIOTECH,
  UAE_LEADERS,
  PRIVACY_LAW_GPT,
  AI_LEADERS,
  AI_BiOMED,
  NAVIGATION_DIAGRAM,
  HALL_OF_FAME_SECTION,
  HALL_OF_FAME,
  REVOLUTION_CUBE,
  MIAMI_MAP,
  INTERACTIVE_MINDMAP_SAAS,
  MULTI_SPACE_3D_SAAS,
  EVOLUTION_TREE_SAAS,
  INVESTTECH_PLATFORM,
  COMPLEX_FRAMEWORK_SAAS,
  DASHBOARD_CONSTRUCTOR,
  SAAS_PROJECTS,
  DYNAMIC_LINE_CHART,
  GEO_DASHBOARDS,
  USA_GEOMAP_STATS_NEW,
  ASIA_MAP_STATS_DARK,
  GEOMAPS_SHOW_SECTION,
  GEO_DASHBOARDS_GLOBAL,
  DASHBOARD_CONSTRUCTOR_V3,
  UK_GEODASHBOARD_2,
  SWITZERLAND_GEODASHBOARD_2,
  TORONTO_MAP,
  ONTARIO_MAP,
  CUBE_5TH_REV,
  BUBBLE_CHART,
  MENA_MAP,
  MINDMAPS_CONSTRUCTION,
  MIAMI_MAP_STATS,
  FLORIDA_MAP_STATS,
  NEW_GENERATION_BUSINESS_DEVELOPMENT_SECTIONS,
  STRATEGIC_ENGAGEMENT_PLAN,
  BIZDEV_PERFOMANCE_REPORT,
  BIZDEV_PERFOMANCE_DASHBOARD,
  LEADS_SECTIONS,
  BIZDEV_PROSPECT_ANALYSIS,
  LEAD_GENERATION_PIPELINE,
  TIER_PLATFORM,
  TIER_PLATFORM_DEEP_INNOVATION,
  TIER_PLATFORM_ECOSYSTEM_MAP,
  TIER_PLATFORM_2,
  TIER_PLATFORM_3,
  HALL_OF_FAME_CONSTRUCTOR,
  DASHBOARD_CONSTRUCTOR_V2,
  PARSING_TEAM,
  PROGRESS_SUMMARY,
  DATA_MANAGEMENT,
  DATA_MANAGEMENT_PROG__DEC_2023,
  DATA_VISUALISATION,
  DATA_VISUALISATION_PROG_DEC_2023,
  TECH_ECO_FIN_DEPT,
  TECH_ECO_FIN_PROG,
  AI_PHARMA_INVEST_DIGEST,
  AI_PHARMA_INVEST_DIGEST_DASH_2,
  AI_PHARMA_INVEST_DIGEST_DASH_3,
  AI_ECO_SIZE_ASSESMENT,
  GLOBAL_AI_ECONOMY,
  AI_ECONOMY_UK,
  AI_ECONOMY_US,
  AI_ECONOMY_BIOMED,
  BIZDEV_TECH_EMAIL_CONSTRUCTOR,
  SALES_MESSAGING_CONSTRUCTOR,
  SMM_PROMOTION_CONSTRUCTOR,
  SAAS_SALES_READY_PROJECTS,
  DASHBOARDS_SALES_READY_PROJECTS,
  SERVICES_SALES_READY_PROJECTS,
  DISTRIBUTOR_PARTNERSHIPS_PLATFORM_SAAS,
  DISTRIBUTOR_PARTNERSHIPS_PLATFORM_DASHBOARDS,
  REPRESENTATIVES_PARTNERSHIPS_PLATFORM,
  ERMS30,
  DASHBOARD_USER_JOURNEY,
  SAAS_USER_JOURNEY,
  BIZDEV_CONSTRUCTOR,
  READYPROJECTS,
  PARTNERSHIPSPLATFORMS,
  USERJOURNEYS,
  QUANTUM_COMPUTING_FRAME,
  IR5TH_PROJECT,
  TECHNO_PROG,
  OE_SMS_DASH2,
  OE_SMS_DASH3,
  BIG_DATA_SYS_DASH2,
  DEEP_PHARMA_INTEL_DASH2,
  INVESTECH_PLAT_DASH2,
  OFF_WORLD_DASH2,
  VALOUR_DASH2,
  BTQ_DASH2,
  FEMTECH_DASH2,
  LONGEVITY_MHEALTH_DASH2,
  BIG_DATA_SYS_DASH3,
  DEEP_PHARMA_INTEL_DASH3,
  INVESTECH_PLAT_DASH3,
  OFF_WORLD_DASH3,
  VALOUR_DASH3,
  BTQ_DASH3,
  FEMTECH_DASH3,
  LONGEVITY_MHEALTH_DASH3,
  TECH_FIN_PLAT_DASH2,
  TECH_FIN_PLAT_DASH3,
  FINANCIAL_TOOLS,
  AMC_PORTFOLIO,
  DEMO_DASHBOARD_COMPETITORS,
  COMPANY_PREDICTIONS,
  LONGEVITY_PORTFOLIO_COMPARITIVE,
  AI_INDUSTRY_COMPANIES,
  AI_INDUSTRY_STATISTICS,
  DEMO_PORTFOLIO_CONSTRUCTOR,
  AI_INDUSTRY_COMPARATIVE_ANALYSIS,
  HEATMAP_ANALYSIS,
  AI_INDUSTRY_COMPETITORS,
  AI_INDUSTRY_PUBLIC_COMPANIES,
  SWITZERLAND_MAP_STATS,
  ADM_PAN_CONST,
  GLOBAL_GEOMAP_STATS_V2,
  GLOBAL_GEOMAP_STATS_V3,
  MULTI_RADAR_CHART,
  MIAMI_GEOMAP,
  HALL_OF_FAME_CONSTRUCTOR_V2,
  TOOLS_COLLECTION,
  TREE_VIZ,
  HARLEY_STREET_2D,
  HARLEY_STREET_3D,
  ADM_PAN_BLACK_CONST,
  MAP_STREET,
  BUILDINGS_MAP_3D,
  MAPBOX_GEDASHBOARD_V1,
  MAP_STREET_3D,
  HEXAGON_V2,
  UK_MAPCHART,
  SOUTH_KOREA_MAP,
  TESSERACT_VIDEO,
  HARLEY_STREET_VIDEO,
  DASHBOARD_CONSTRUCTOR_V3_VIDEO,
  KEY_IND_RESP,
  PIE_CHAR_LABEL,
  NO_CODE_MAPS,
  TIME_MACHINE,
  MIND_NO_CODE_3D,
  NO_CODE_SECTION,
  ECOS_MAP_TOOLS_SECTION,
  PORTFOLIO_CONSTRUCTION_TOOL,
  DASHBOARD_COMPETITOR,
  ISRAEL_MAP_STATS,
  FLOW_CHART_V2,
  CLUSTERED_NETWORK_DIAGRAM,
  NETWORK_DIAGRAM,
  DOCUMENT_CREATOR_V3,
  HARLEY_STREET_3D_CHINAU,
  DASHBOARD_STATISTICS,
  GLOBAL_GEOMAP_STATS_V4,
  PAGE_BUILDER,
  ECOSYSTEM_TOOLS,
  INTERACTIVE_MINDMAP_ECO,
  STATS_MACRO,
} from "./diagram";

export const NAMES = {
  [COMPANIES_LIST_COLOR]: "Companies List Color",
  [PORTFOLIO_CONSTRUCTION_TOOL]: "Portfolio Constructor",
  [DASHBOARD_COMPETITOR]: "Competitor Analysis Tool",
  [DASHBOARD_STATISTICS]: "Dashboard Statistics",
  [DOCUMENT_CREATOR_V2]: "Document Creator V2",
  [DOCUMENT_CREATOR_V3]: "Document Creator V3",
  [GEO_DESHBOARDS]: "Geo Dashboard Constructor",
  [GEO_DESHBOARDS_V2]: "Geo Dashboard Constructor",
  [GEO_DESHBOARDS_NO_CODE]: "Geo Dashboard Constructor No Code",
  [PSEUDO_PYRAMID]: "Pyramid Pseudo Mindmap",
  [USA_GEOMAP]: "USA GeoMap",
  [FRAME_CONSTRUCTOR]: "Framework Constructor",
  [EUROPE_MAP]: "Europe GeoMap",
  [GLOBAL_GEOMAP]: "Global GeoMap",
  [GLOBAL_GEOMAP_STATS]: "Global GeoDashboard 1.0",
  [GEOMAPS_SECTION]: "GeoMaps",
  [GEOMAPS_SHOW_SECTION]: "GeoDashboards",
  [DIGITAL_UK]: "Digital UK",
  [UK_MAP]: "UK GeoMap",
  [UAE_MAP]: "UAE GeoMap",
  [SWITZERLAND_MAP]: "Switzerland GeoMap",
  [MOLDOVA_MAP]: "Moldova GeoMap",
  [TUBE_TREE_3D]: "Tube Tree 3D",
  [VERTICAL_BAR_FOR_MAP]: "Vertical Bar For GeoMaps",
  [UNIVERSAL_BAR]: "Universal Bar",
  [TIME_MACHINE]: "Time Machine",
  [MIND_NO_CODE_3D]: "Circular Mindmap 3D No Code",
  [NO_CODE_MAPS]: "No Code Maps",
  [KEY_IND_RESP]: "Key Indicators",
  [PIE_CHAR_LABEL]: "Pie Chart",
  [IT_PLATFROMS_REGISTRY]: "IT Platforms registry",
  [REGISTERY_FRONTEND_ALL]: "completed Frontend Registry",
  [REGISTERY_FRONTEND_INDEVELOPMENT]: "in development Registry",
  [REGISTERY_DASHBOARD]: "Dashboards registry",

  [PYRAMID]: "Benchmark Tool Pyramid 2D",
  [PYRAMID_3D]: "Benchmark Tool Pyramid 3D",
  [COMPANIES_LIST]: "Companies list",
  [MOLDOVA_MAP_V2]: "Moldova with Pictograms",
  [COMPANIES_TABLE]: "Companies table",
  [MARQUEE_LIST_BAR]: "Marquee bar",
  [TABLE_WITH_BAR]: "Table with Bars",
  [LIST_WITH_BAR]: "List with bar",
  [CUBE_3D]: "Cube 3D",
  [TREE_3D]: "Evolution Tree 3D",
  [PIE_CHART_3D]: "Pie chart 3D",
  [NODE_CHART_3D]: "Node Chart 3D",
  [GLOBE_CHART_3D]: "Globe Chart 3D",
  [STACKED_BAR_CHART]: "Stacked Bar Chart",
  [VERTICAL_BAR_DIFF]: "Vertical Bars Diff",
  [BAR_CHART_3D]: "Bar Chart 3D",
  [CUSTOM_TABLE]: "Custom Table",
  [INTERACTIVE_PANEL]: "Navigation Panel",
  [INTERACTIVE_PANEL_COLOR]: "Navigation Panel Color",
  [INTERACTIVE_PANEL_LOGO]: "Navigation Panel Logo",
  [TREE]: "Evolution Tree",
  [MIND_MAP]: "Circular Pseudo Mindmap",
  [TREE_V2]: "Evolution Tree V2",
  [TREE_NO_DATE]: "Tree Without Date",
  [DECISION_TREE]: "Decision Tree",
  [RADIAL_TREE]: "Radial Tree",
  [REVOLUTION_CUBE_3D]: "Revolution 3D Cube",
  [DOCUMENT_CREATOR]: "Document Creator",
  [NUM2]: "Horizontal Bar Chart",
  [NUM3]: "Ranking with images",
  [NUM4]: "Vertical Bar Chart",
  [RECT_MINDMAP]: "Rectangle Pseudo Mindmap",
  [NUM4_5]: "Round balloons",
  [NUM5]: "Vertical bar chart 3D",
  [NUM9]: "Ball Snake",
  [NUM11]: "Ranking Table",
  [NUM14]: "Round Lists",
  [NUM15]: "Round Numbers",
  [NUM18_1]: "Round cumulative benchmark",
  [CUBE_5TH_REV]: "Complex 3D Framework for Advance Tech Industries",
  [NUM13]: "Horizontal Bars Stacked",
  [P3D]: "Pie 3D",
  [CIRCLE_INTERACTIVE]: "Circle Interactive",
  [RECTUNGULAR_INTERACTIVE]: "Rectangular Interactive",
  [ADMIN_BUTTONS]: "Navigation Spreadsheet Style",
  [MIND_MAPS_MENU]: "MindMaps",
  [GRAPHS_MENU]: "Graphs",
  [TOOLS_MENU]: "Tools",
  [ORGANISATIONAL_STRUCTURE]: "Organisational Structure",
  [FRONTEND_TOOLS_LIBRARY_MENU]: "frontend tools library",
  [INTERACTIVE_MINDMAPS_MENU]: "Interactive Mindmaps",
  [INTERACTIVE_MINDMAPS_SECTION]: "Interactive Mindmaps",
  [BAR_CHARTS_SECTION]: "Charts",
  [LISTS_SECTION]: "Lists",
  [COMPARISON_SWOTS]: "Comparison SWOTs",
  [OTHER_SECTION]: "Others",
  [MIND_MAPS_SECTION]: "Mind Maps",
  [FRONTEND_TOOLS_LIBRARY_SECTION]: "frontend tools library",
  [INFOGRAPHICS_SECTION]: "Macroparameters",
  [NAVIGATION_MENU_SECTION]: "Navigation Menu",
  [TOOLS]: "Tools",
  [ADMIN_BUTTONS_SECTION]: "Navigation Spreadsheet Style",

  [FRONTEND_TOOLS_LIBRARY_MENU]: "frontend tools library",
  [INTERACTIVE_MINDMAPS_MENU]: "Interactive Mindmaps",
  [INTERACTIVE_MINDMAPS_SECTION]: "Interactive Mindmaps",
  [BAR_CHARTS_SECTION]: "Charts",
  [LISTS_SECTION]: "Lists",
  [COMPARISON_SWOTS]: "Comparison SWOTs",
  [OTHER_SECTION]: "Others",
  [MIND_MAPS_SECTION]: "Mind Maps",
  [FRONTEND_TOOLS_LIBRARY_SECTION]: "frontend tools library",
  [INFOGRAPHICS_SECTION]: "Macroparameters",
  [NAVIGATION_MENU_SECTION]: "Navigation Menu",
  [TOOLS]: "Tools",
  [ADMIN_BUTTONS_SECTION]: "Navigation Spreadsheet Style",
  [DOUGHNUT_CHART]: "Doughnut Chart",
  [LEADER_BOARD]: "Leader Board",
  [TUBE_MAP]: "Tube Map",
  [FORCE_DIRECTED_TREE]: "Force Directed Tree",
  [HEAT_MAP]: "Heat Map",
  [HEAT_MAP_GRID]: "Heat Map Grid",
  [DEALS_STRUCTURE]: "Deals Structure",
  [TREE_MAP]: "Tree Map",
  [NEW_GENERATION_TOOLS_SECTION]:
    "Major Universal Constructors (Major No-Code Tool Constructors and Assemblers)",
  [ECOS_MAP_TOOLS_SECTION]: "Ecosystem Mapping Constructor No-code solutions",
  [NO_CODE_SECTION]: "No Code Tools",
  [BUSS_INT_DEP]: "Business Intelligence Department",
  [IT_DEPT]: "IT Department",
  [ADMIN_TECH_DEPT]: "AdminTech Department",
  [LEGAL_TECH_DEPT]: "LegalTech Department",
  [DATA_SCIENCE_TECH_DEPT]: "Data Science Department",
  [BIZDEVTECH_DEPT]: "BizDevTech Department",
  [ACCOUNTING_DEPT]: "Accounting Department",
  [GENERIC_PASSWORDS]: "Generic Passwords",
  [DOMAINS_REGISTRY]: "Domains Registry",
  [LONGEVITY_GPT]: "Longevity GPT",
  [LEGAL_EAGLE_GPT]: "Legal Eagle GPT",
  [IT_DEPT_GPT]: "IT Department GPT",
  [DATA_MNGMNT_GPT]: "Data Management GPT",
  [DASHBOARDS_MENU]: "Dashboards",
  [ORGANIZATIONS]: "Organization",
  [PERSONALITIES]: "Personalities",
  [CUSTOM_ENTITIES]: "Custom Entities",
  [GENERIC_I_FRAMES]: "Generic iFrames",
  [MINDMAPS]: "Mindmaps",
  [DASHBOARDS_TOOLS]: "Dashboard Tools",
  [PHILANTHROPY_DEPT]: "Philanthropy Department",
  [INFOGRAPHICS_SECTION]: "Macroparameters",
  [NAVIGATION_MENU_SECTION]: "Navigation Menu",
  [TOOLS]: "Tools",
  [ADMIN_BUTTONS_SECTION]: "Navigation Spreadsheet Style",
  [DKG_INTERNAL_SECTION]: "DKG Internal",
  [REGISTERIES_MENU]: "Registries",
  [AI_AGENTS_SECTION]: "AI Agents",
  [DATABOX_DASHBOARDS_SECTION]: "Databox Dashboards",
  [DATABASE_MANAGEMENT_SYSTEM_MENU]: "Database Management System",
  [NEXT_GEN_SECTION]: "Next Generation Projects",
  [THE_5_IND]: "The 5th Industrail Revolution",
  [MDVS]: "MDVS",
  [DPI2_0]: "DPI 2.0",
  [OPER_ENV_SYSTEM_SECTION]: "Operational Environment & Smart Matching System",
  [OPER_ENV_VAL]: "Operational Environment: Valour",
  [BDAS]: "Big Data Analytics System (BDAS)",
  [DEEP_PHARMA]: "Deep Pharma Intelligence (DPI)",
  [INV_TECH_PLATFORM]: "InvestTech Platform",
  [LONG_M_HEALTH]: "Longevity mHealth",
  [THECH_FIN_PLATF]: "TechFinance Platforms",
  [OFF_WORLD]: "OffWorld",
  [BTQ]: "BTQ",
  [ADM_PAN_CONST]: "Admin Panels Constructor 2.0",
  [ADM_PAN_BLACK_CONST]: "Dark Admin Panels Constructor",
  [VALOUR]: "Valour",
  [NORTH_IRELAND_MAP]: "North Ireland GeoMap",
  [NORTH_IRELAND_MAP_STATS]: "North Ireland GeoDashboard 1.0",
  [FRANCE_MAP]: "France GeoMap",
  [LONDON_MAP_DARK]: "LondonMapDark",
  [LONDON_STATS_DARK]: "London Dark GeoDashboard 1.0",
  [CANADA_MAP]: "Canada GeoMap",
  [UK_STATS_DARK]: "UK Dark GeoDashboard 1.0",
  [UK_MAP_DARK]: "UK Map Dark",
  [CHINA_MAP_STATS]: "China GeoDashboard 1.0",
  [UK_MAP_STATIC]: "UK Static GeoDashboard 1.0",
  [MOLDOVA_MAP_STATS]: "Moldova GeoDashboard 1.0",
  [ISRAEL_MAP]: "Israel Geomap",
  [JAPAN_MAP]: "Japan Geomap",
  [CIRCULAR_INFOGRAPH_UK]: "Circular Infograph UK",
  [TIME_SERIES_CHART]: "Time Series Chart",
  [PROMO_BANNER]: "Promo Banner",
  [ASIA_MAP_STATS_DARK]: "Asia Dark GeoDashboard 1.0",
  [USA_GEOMAP_STATS_NEW]: "USA GeoDashboard 1.0",
  [ORGANISATIONAL_STRUCTURE]: "Organisational Structure",
  [DKG_INTERNAL_SECTION]: "DKG Internal",
  [GEO_DASHBOARDS]: "GeoDashboard Constructor 2.0",
  [DYNAMIC_LINE_CHART]: "Dynamic Line Chart",
  [LEADER_BOARD]: "Leader Board",
  [HEAT_MAP]: "Heat Map",
  [HEAT_MAP_GRID]: "Heat Map Grid",
  [TREE_MAP]: "Framework",
  [FLOW_CHART]: "Flow Chart",
  [FLOW_CHART_V2]: "Flow Chart V2",
  [FORCE_DIRECTED_TREE]: "Force Directed Tree (Metro)",
  [DATA_SCIENCE_TECH_DEPT]: "Data Science Department",
  [IT_DEPT]: "IT Department",
  [SAAS_PROJECTS]: "SaaS Projects",
  [LEGAL_TECH_DEPT]: "LegalTech Department",
  [DASHBOARD_CONSTRUCTOR]: "Dashboard Constructor SaaS",
  [COMPLEX_FRAMEWORK_SAAS]: "Complex Framework SaaS",
  [INVESTTECH_PLATFORM]: "InvestTech Platform",
  [EVOLUTION_TREE_SAAS]: "Complex Evolution Trees SaaS",
  [MULTI_SPACE_3D_SAAS]: "3D Multidimensional Space SaaS",
  [INTERACTIVE_MINDMAP_SAAS]: "Interactive Mindmaps SaaS",
  [IT_DEPT_GPT]: "IT Department GPT",
  [LEGAL_EAGLE_GPT]: "Legal Eagle GPT",
  [MIAMI_MAP]: "Miami GeoMap",
  [REVOLUTION_CUBE]: "Complex 3D Framework for Advance Tech Industries",
  [HALL_OF_FAME]: "Hall of Fame",
  [HALL_OF_FAME_SECTION]: "Hall of Fame",
  [ADMIN_TECH_DEPT]: "AdminTech Department",
  [DATA_MNGMNT_GPT]: "Data Management GPT",
  [NAVIGATION_DIAGRAM]: "Navigation Diagram",
  [BIZDEVTECH_DEPT]: "BizDevTech Department",
  [AI_BiOMED]: "AI in Biomed Leaders UK",
  [AI_LEADERS]: "AI Leaders",
  [PRIVACY_LAW_GPT]: "Privacy Law Navigator AI",
  [UAE_LEADERS]: "UAE Leaders MindMap",
  [AI_BIOTECH]: "AI in BioTech Leaders",
  [AI_HEALTHTECH]: "AI in HealthTech Leaders",
  [AI_NEUROTECH]: "AI in NeuroTech Leaders",
  [INT_MINDMAP]: "Interactive Mindmap",
  [RECTANGLE_MINDMAP]: "Rectangle Mindmaps",
  [D3D_SECTION]: "3D Visualisations",
  [ACCOUNTING_DEPT]: "Accounting Department",
  [LIFE_SCIENCES_DEPT]: "Life Sciences Department",
  [GOVTECH_GPT]: "GovTech GPT",
  [PHILANTHROPY_GPT]: "Philanthropy GPT",
  [GOVTECH_DEPT]: "GovTech Department",
  [PHILANTHROPY_DEPT]: "Philanthropy Department",
  [LONGEVITY_BOOKS]: "Longevity Books",
  [WEF_PANEL]: "WEF-like Navigation Panel",
  [GEO_DASHBOARDS_V2_MOLDOVA_GENERAL]: "Geo Dashboard 2.0 Moldova",
  [GEO_DASHBOARDS_V2_MOLDOVA_EL]: "Geo Dashboard 2.0 Moldova",
  [GEO_DASHBOARDS_V2_MOLDOVA_EN]: "Geo Dashboard 2.0 Moldova",
  [GEO_DASHBOARDS_V2_MOLDOVA_USA]: "Geo Dashboard 2.0 USA",
  [GEO_DASHBOARDS_V2_MOLDOVA_NC]: "Norbert Czimadia",
  [AI_UK_GPT]: "AI in UK GPT",
  [AI_FINANCE_GPT]: "AI in Finance Hub and Accelerator GPT",
  [BUSSINESS_INTELLIGENCE_GPT]: "Business Intelligence GPT",
  [LEGAL_LENS_GPT]: "Legal Lens GPT",
  [ADMIN_ASSISTANT_GPT]: "Admin Assistant GPT",
  [PLATFORM_SOLUTIONS_GPT]: "Platform Solutions GPT",
  [INSIGHT_WRITER_GPT]: "Insight Writer GPT",
  [PR_SMM_TRANSFORMER_GPT]: "PR to SMM Transformer GPT",
  [HALL_OF_FAME_BANNER]: "Hall of Fame Banner",
  [PSEUDO_PYRAMID]: "Ecosystem Benchmark Pyramid Mindmap",
  [USA_GEOMAP]: "USA GeoDashboard 1.0",
  [EUROPE_MAP]: "Europe GeoMap",
  [GLOBAL_GEOMAP]: "Global GeoMap",
  [GEOMAPS_SECTION]: "GeoDashboards",
  [TECHNO_DASHBOARD]: "Techno Policy Geo Dashboard",
  [MAPS_SECTION]: "GeoMaps",
  [FRAMEWORK_CONSTRUCTOR]: "Framework Constructor",
  [DIGITAL_UK]: "Digital UK",
  [UK_MAP]: "UK GeoMap",
  [UAE_MAP]: "UAE GeoMap",
  [SWITZERLAND_MAP]: "Switzerland GeoMap",
  [MOLDOVA_MAP]: "Moldova GeoMap",
  [VERTICAL_BAR_FOR_MAP]: "Vertical Bar For GeoMaps",
  [UNIVERSAL_BAR]: "Universal Bar",
  [IT_PLATFROMS_REGISTRY]: "IT Platforms registry",
  [REGISTERY_FRONTEND_ALL]: "completed Frontend Registry",
  [REGISTERY_FRONTEND_INDEVELOPMENT]: "in development Registry",
  [REGISTERY_DASHBOARD]: "Dashboards registry",
  [PYRAMID]: "Interactive 2D Benchmark",
  [PYRAMID_3D]: "Interactive 3D Benchmark",
  [COMPANIES_LIST]: "Companies list",
  [MOLDOVA_MAP_V2]: "Moldova with Pictograms",
  [COMPANIES_TABLE]: "Companies table",
  [MARQUEE_LIST_BAR]: "Marquee bar",
  [HALL_OF_FAME_CONSTRUCTOR]: "Hall Of Fame Constructor",
  [HALL_OF_FAME_CONSTRUCTOR_V2]: "Hall of Objects Constructor",
  [TOOLS_COLLECTION]: "Tools Collection",
  [TABLE_WITH_BAR]: "Table with Bars",
  [LIST_WITH_BAR]: "List with bar",
  [CUBE_3D]: "Cube 3D",
  [TREE_3D]: "Complex Evolution Tree",
  [TUBE_TREE_3D]: "Tube Evolution Tree 3D",
  [LONGEVITY_GPT]: "Longevity GPT",
  [PIE_CHART_3D]: "Pie chart 3D",
  [NODE_CHART_3D]: "Radial Timeline 3D",
  [GLOBE_CHART_3D]: "Globe Chart 3D",
  [STACKED_BAR_CHART]: "Stacked Bar Chart",
  [VERTICAL_BAR_DIFF]: "Vertical Bars Diff",
  [BAR_CHART_3D]: "Bar Chart 3D",
  [CUSTOM_TABLE]: "Custom Table",
  [INTERACTIVE_PANEL]: "Navigation Panel",
  [INTERACTIVE_PANEL_COLOR]: "Navigation Panel Color",
  [TREE]: "Navigation Interactive Network",
  [MIND_MAP]: "Circular Big Ecosystem Mindmap",
  [TREE_V2]: "Interactive Evolution Tree",
  [TREE_NO_DATE]: "Tree Without Date",
  [DECISION_TREE]: "Decision Tree",
  [RADIAL_TREE]: "Radial Tree",
  [REVOLUTION_CUBE_3D]: "Revolution 3D Cube",
  [DOCUMENT_CREATOR]: "Document Creator",
  [NUM2]: "Horizontal Bar Chart",
  [NUM3]: "Ranking with images",
  [NUM4]: "Vertical Bar Chart",
  [RECT_MINDMAP]: "Rectangle Big Ecosystem Mindmap",
  [NUM4_5]: "Round balloons",
  [NUM5]: "Vertical bar chart 3D",
  [NUM9]: "Ball Snake",
  [BUSS_INT_DEP]: "Business Intelligence Department",
  [NUM11]: "Ranking Table",
  [NUM14]: "Interactive Macroparameters Panel Lists",
  [NUM15]: "Interactive Macroparameters Panel Numbers",
  [NUM18_1]: "Round Cumulative Benchmark",
  [UK_TUBE]: "3D Multidimensional Space Tube",
  [VALINOR]: "Valinor",
  [BOOK_LIBRARY]: "Books Library",
  [NUM13]: "Horizontal Bars Stacked",
  [P3D]: "Pie 3D",
  [CIRCLE_INTERACTIVE]: "Circle Interactive",
  [RADAR_CHART_BLURRED]: "SWOT Analysis",
  [RECTUNGULAR_INTERACTIVE]: "Rectangular Interactive",
  [ADMIN_BUTTONS]: "Navigation Spreadsheet Style",
  [MIND_MAPS_MENU]: "MindMaps",
  [GRAPHS_MENU]: "Graphs",
  [TOOLS_MENU]: "Tools",
  [FRONTEND_TOOLS_LIBRARY_MENU]: "frontend tools library",
  [INTERACTIVE_MINDMAPS_MENU]: "Interactive Mindmaps",
  [INTERACTIVE_MINDMAPS_SECTION]: "Interactive Mindmaps",
  [AI_AGENTS_SECTION]: "AI Agents",
  [BAR_CHARTS_SECTION]: "Charts",
  [LISTS_SECTION]: "Lists",
  [COMPARISON_SWOTS]: "Comparison SWOTs",
  [OTHER_SECTION]: "Others",
  [MIND_MAPS_SECTION]: "Mind Maps",
  [MIND_MAPS_3D_SECTION]: "3D Mind Maps",
  [INTERACTIVE_3D_SECTION]: "Multidimensional 3D Interactive System",
  [SWOT_SECTION]: "SWOT Analysis Instruments",
  [TIME_LINE_SECTION]: "Timelines",
  [FRONTEND_TOOLS_LIBRARY_SECTION]: "frontend tools library",
  [INFOGRAPHICS_SECTION]: "Macroparameters",
  [NAVIGATION_MENU_SECTION]: "Navigation Menu Panels",
  [TOOLS]: "Tools",
  [ADMIN_BUTTONS_SECTION]: "Navigation Spreadsheet Style",
  [HEXAGON]: "Advanced Frameworks",
  [BAR_CHARTS_MENU]: "Charts",
  [LISTS_MENU]: "Lists",
  [INFOGRAPHICS_MENU]: "Macroparameters",
  [NAVIGATION_ELEMENTS_MENU]: "Navigation Panels SaaS",
  [OTHERS_MENU]: "Others",
  [D3D_MENU]: "3D Graphs",
  [SERPENTINE_PATH]: "Serpentine Path",
  [TIMELINE_HORIZONTAL]: "Timeline Horizontal",
  [DATABASE_MANAGEMENT_SYSTEM_MENU]: "Database Management System",
  [DASHBOARDS_MENU]: "Dashboards",
  [DATABOX_DASHBOARDS_MENU]: "Databox Dashboards",
  [DATABOX_DASHBOARDS_SECTION]: "Databox Dashboards",
  [AI_UK_DATABASE]: "AI in UK DataBase Status",
  [AI_ECOSYSTEM_DATABASE]: "AI Ecosystem DataBase Status",
  [PHILANTRHROPY_INTERNATIONAL]: "Philantrhropy International",
  [TIME_LINE]: "Timeline",
  [HUBSPOT_METRICS]: "Hubspot Metrics",
  [GOOGLE_ANALYTICS]: "Google Analytics",
  [FEMTECH_ANALYTICS_LINKEDIN]: "Femtech Analytics Linkedin",
  [AIIA_SOCIAL_MEDIA_ANALYTICS]: "AiiA Social Media Analytics",
  [AIIA]: "AiiA",
  [COMPARATIVE_ANALYSIS_LINKEDIN]: "Comparative Analysis Linkedin",
  [INVEST_IN_UKRAINE_TECH]: "Invest In Ukraine Tech",
  [GLOBAL_AI_ECOSYSTEM]: "Global Ai Ecosystem",
  [DATA_ANALYTICS_PLATFORM]: "Data Analytics Platform",
  [IN_DEVELOPMENT_MENU]: "In Development",
  [ADMIN_BUTTONS_MENU]: "Navigation Spreadsheet Style",
  [REGISTERIES_MENU]: "Registries",
  [FOR_REVISION]: "For Revision",
  [FOR_REVISION_MENU]: "For Revision",
  [FOR_REVISION_SECTION]: "For Revision",
  [PENTAGON_3D]: "Pentagon 3D",
  [NUM18]: "Horizontal Animated Bars",
  [IN_DEVELOPMENT_SECTION]: "In Development",
  [CURRENT_STATE_FEEDBACK]: "Current State Feedback",
  [SUGGEST_FEATURE]: "Suggest Feature",
  [PLANNED_FRONTEND_TOOLS]: "Planned Frontend Tools",
  [COMPARISON_BARS]: "Comparison Bars",
  [SWOT_3D]: "SWOT 3D",
  [LINE_CHART]: "Line Chart",
  [GAUGE_CHART]: "Gauge Chart",
  [KEY_INDICATOR]: "Key Indicators",
  [DOCUMENT_CREATOR_SECTION]: "Document Creator",
  [ORGANIZATIONS]: "Organization",
  [PERSONALITIES]: "Personalities",
  [CUSTOM_ENTITIES]: "Custom Entities",
  [GENERIC_I_FRAMES]: "Generic iFrames",
  [MINDMAPS]: "Mindmaps",
  [DASHBOARDS_TOOLS]: "Database Management",
  [TREES_AND_PATHWAYS]: "Trees and Pathways",
  [TREES_AND_PATHWAYS_MENU]: "Trees and Pathways",
  [MIND_MAP_REGISTRY]: "Mindmaps Registry",
  [GENERIC_PASSWORDS]: "Generic Passwords",
  [DOMAINS_REGISTRY]: "Domains Registry",
  [BENCHMARK_TOOLS_MENU]: "Benchmark Interactive Tools",
  [BENCHMARK_TOOLS_SECTION]: "Benchmark Tools",
  [CIRCULAR_MINDMAP_3D]: "Interactive 3D Ecosystem Map",
  [MULTI_CUBE_3D]: "Multi Cube 3D",
  [RADAR_CHART_MENU]: "Radar Chart",
  [RADAR_CHART_SECTION]: "Radar Chart",
  [RADAR_CHART]: "Radar Chart",
  [LONDON_MAP]: "London GeoMap",
  [LONDON_MAP_STATS]: "London GeoDashboard 1.0",
  [UAE_GEO_MAP_STATS]: "UAE GeoDashboard 1.0",
  [WALES_MAP_STATS]: "Wales GeoDashboard 1.0",
  [CHISINAU_MAP]: "Chisinau GeoMap",
  [ASIA_MAP]: "Asia GeoMap",
  [WALES_MAP]: "Wales GeoMap",
  [GULF_REGION_MAP]: "Gulf GeoDashboard 1.0",
  [UK_MAP_STATS]: "UK GeoDashboard 1.0",
  [UK_MAP_NEW]: "UK Light GeoDashboard 1.0",
  [GERMANY_MAP]: "Germany GeoMap",
  [SCOTLAND_MAP]: "Scotland GeoMap",
  [MANCHESTER_MAP]: "Manchester GeoMap",
  [SCOTLAND_MAP_STATS]: "Scotland GeoDashboard 1.0",
  [MANCHESTER_MAP_STATS]: "Manchester GeoDashboard 1.0",
  [NORTH_IRELAND_MAP]: "North Ireland",
  [ARROW_PROGRESS_CHART]: "Arrow Progress Chart",
  [GEO_DASHBOARDS_GLOBAL]: "Global Geo Dashboard 2.0",
  [DASHBOARD_CONSTRUCTOR_V3]: "Dashboard Constructor 3.0",
  [UK_GEODASHBOARD_2]: "UK Geo Dashboard 2.0",
  [SWITZERLAND_GEODASHBOARD_2]: "Switzerland Geo Dashboard 2.0",
  [TORONTO_MAP]: "Toronto GeoMap",
  [ONTARIO_MAP]: "Ontario GeoMap",
  [BUBBLE_CHART]: "Bubble Chart",
  [MENA_MAP]: "MENA GeoMap",
  [MINDMAPS_CONSTRUCTION]: "Mindmaps Constructor",
  [MIAMI_MAP_STATS]: "Miami GeoDashboard 1.0",
  [FLORIDA_MAP_STATS]: "Florida GeoDashboard 1.0",
  [NEW_GENERATION_BUSINESS_DEVELOPMENT_SECTIONS]: "BizDev Performance",
  [STRATEGIC_ENGAGEMENT_PLAN]: "Strategic Engagement Plan",
  [BIZDEV_PERFOMANCE_REPORT]: "BizDev Performance Report",
  [BIZDEV_PERFOMANCE_DASHBOARD]: "BizDev Performance Dashboard",
  [LEADS_SECTIONS]: "Leads",
  [BIZDEV_PROSPECT_ANALYSIS]: "BizDev Prospect Analysis",
  [LEAD_GENERATION_PIPELINE]: "Lead Generation Pipeline",
  [TIER_PLATFORM]: "Tier Platform",
  [TIER_PLATFORM_DEEP_INNOVATION]: "Tier 1 Platform: Deep-Innovation",
  [TIER_PLATFORM_ECOSYSTEM_MAP]: "Tier 1 Platform: Ecosystem Map",
  [TIER_PLATFORM_2]: "Tier 2 Platform",
  [TIER_PLATFORM_3]: "Tier 3 Platform",
  [BIZDEV_TECH_EMAIL_CONSTRUCTOR]: "BizDevTech Email Constructor",
  [SALES_MESSAGING_CONSTRUCTOR]: "Sales Messaging Constructor",
  [SMM_PROMOTION_CONSTRUCTOR]: "SMM Promotion Constructor",
  [SAAS_SALES_READY_PROJECTS]: "SaaS Sales Ready Projects",
  [DASHBOARDS_SALES_READY_PROJECTS]: "Dashboards Sales Ready Projects",
  [SERVICES_SALES_READY_PROJECTS]: "Services Sales Ready Projects",
  [DISTRIBUTOR_PARTNERSHIPS_PLATFORM_SAAS]:
    "Distributor Partnerships Platform (SaaS)",
  [DISTRIBUTOR_PARTNERSHIPS_PLATFORM_DASHBOARDS]:
    "Distributor Partnerships Platform (Dashboards)",
  [REPRESENTATIVES_PARTNERSHIPS_PLATFORM]:
    "Representatives-Partnerships Platform",
  [ERMS30]: "ERMS 3.0",
  [DASHBOARD_USER_JOURNEY]: "Dashboard User Journey",
  [SAAS_USER_JOURNEY]: "SaaS User Journey",
  [DASHBOARD_CONSTRUCTOR_V2]: "Dashboard Constructor 2.0",
  [PARSING_TEAM]: "Parsing Team",
  [PROGRESS_SUMMARY]: "Progress Summary",
  [DATA_MANAGEMENT]: "Data Management",
  [DATA_MANAGEMENT_PROG__DEC_2023]: "December 2023 Data Management Progress",
  [DATA_VISUALISATION]: "Data Visualization",
  [DATA_VISUALISATION_PROG_DEC_2023]:
    "December 2023 Data Visualisation Progress",
  [TECH_ECO_FIN_DEPT]: "Tech Economy & Finance Department",
  [TECH_ECO_FIN_PROG]: "Tech Economy & Finance Progress Summary",
  [AI_PHARMA_INVEST_DIGEST]: "AI Pharma Investment Digest",
  [AI_PHARMA_INVEST_DIGEST_DASH_2]: "Dashboard 2.0",
  [AI_PHARMA_INVEST_DIGEST_DASH_3]: "Dashboard 3.0",
  [AI_ECO_SIZE_ASSESMENT]: "AI Economy Size Assessment GeoDashboards",
  [GLOBAL_AI_ECONOMY]: "Global AI Economy",
  [AI_ECONOMY_UK]: "AI Economy in UK",
  [AI_ECONOMY_US]: "AI Economy in US",
  [AI_ECONOMY_BIOMED]: "AI Economy  in BioMed",
  [BIZDEV_CONSTRUCTOR]: "BizDev Constructors",
  [READYPROJECTS]: "Ready Projects",
  [PARTNERSHIPSPLATFORMS]: "Partnerships Platforms",
  [USERJOURNEYS]: "User Journeys",
  [QUANTUM_COMPUTING_FRAME]: "Quantum Computing FrameWork",
  [IR5TH_PROJECT]: "5-IR",
  [TECHNO_PROG]: "Technologies Progress",
  [OE_SMS_DASH2]: "OE-SMS Dashboards 2.0",
  [OE_SMS_DASH3]: "OE-SMS Dashboards 3.0",
  [BIG_DATA_SYS_DASH2]: "Big Data Analytics System (BDAS)",
  [DEEP_PHARMA_INTEL_DASH2]: "Deep Pharma Intelligence (DPI)",
  [INVESTECH_PLAT_DASH2]: "InvestTech Platform",
  [OFF_WORLD_DASH2]: "OffWorld",
  [VALOUR_DASH2]: "Valour",
  [BTQ_DASH2]: "BTQ",
  [FEMTECH_DASH2]: "FemTech",
  [TECH_FIN_PLAT_DASH2]: "TechFinance Platforms",
  [LONGEVITY_MHEALTH_DASH2]: "Longevity mHealth",
  [BIG_DATA_SYS_DASH3]: "Big Data Analytics System (BDAS)",
  [DEEP_PHARMA_INTEL_DASH3]: "Deep Pharma Intelligence (DPI)",
  [INVESTECH_PLAT_DASH3]: "InvestTech Platform",
  [OFF_WORLD_DASH3]: "OffWorld",
  [VALOUR_DASH3]: "Valour",
  [BTQ_DASH3]: "BTQ",
  [FEMTECH_DASH3]: "FemTech",
  [TECH_FIN_PLAT_DASH3]: "TechFinance Platforms",
  [LONGEVITY_MHEALTH_DASH3]: "Longevity mHealth",
  [FINANCIAL_TOOLS]: "Financial Engineering Tools",
  [AMC_PORTFOLIO]: "AMC Portfolio",
  [AI_INDUSTRY_COMPARATIVE_ANALYSIS]: "AI Industry Comparative Analysis",
  [DEMO_PORTFOLIO_CONSTRUCTOR]: "Demo Portfolio Constructor",
  [AI_INDUSTRY_STATISTICS]: "AI Industry Statistics",
  [AI_INDUSTRY_COMPANIES]: "AI Industry Companies",
  [LONGEVITY_PORTFOLIO_COMPARITIVE]: "Longevity Portfolio Comparative",
  [COMPANY_PREDICTIONS]: "Company Predictions",
  [DEMO_DASHBOARD_COMPETITORS]: "Demo dashboard Competitors",
  [HEATMAP_ANALYSIS]: "Heatmap Analysis",
  [AI_INDUSTRY_COMPETITORS]: "AI Industry Competitors",
  [AI_INDUSTRY_PUBLIC_COMPANIES]: "AI Industry Public Companies",
  [GLOBAL_GEOMAP_STATS_V2]: "Global GeoDashboard 1.0 V2",
  [SWITZERLAND_MAP_STATS]: "Switzerland GeoDashboard 1.0 V2",
  [GLOBAL_GEOMAP_STATS_V3]: "Global GeoDashboard 1.0 V3",
  [MULTI_RADAR_CHART]: "Multi Dataset Comparison SWOT",
  [MIAMI_GEOMAP]: "Miami GeoMap",
  [TREE_VIZ]: "Pathways Tree",
  [HARLEY_STREET_2D]: "Harley Street 2D Map",
  [HARLEY_STREET_3D]: "Harley Street 3D Map",
  [BUILDINGS_MAP_3D]: "3D Map with Buildings",
  [MAP_STREET]: "2D Map with filters",
  [MAPBOX_GEDASHBOARD_V1]: "Mapbox with GeoDashboard 1.0",
  [MAP_STREET_3D]: "3D Map with filters",
  [HEXAGON_V2]: "Advanced Frameworks V2",
  [UK_MAPCHART]: "UK Map Constructor",
  [SOUTH_KOREA_MAP]: "South Korea Map",
  [TESSERACT_VIDEO]:
    "Multi-Dimensional Vector Space and Operational Environment Advanced Visualisation System",
  [HARLEY_STREET_VIDEO]: "Longevity Clinics Metaverse",
  [HARLEY_STREET_3D_CHINAU]: "Chisinau 3D",
  [DASHBOARD_CONSTRUCTOR_V3_VIDEO]: "Dashboard Constructor V3",
  [ISRAEL_MAP_STATS]: "Israel GeoDashboard 1.0",
  [CLUSTERED_NETWORK_DIAGRAM]: "Clustered Network Diagram",
  [NETWORK_DIAGRAM]: "Network Diagram",
  [GLOBAL_GEOMAP_STATS_V4]: "Global GeoDashboard 1.0 V4",
  [PAGE_BUILDER]: "Page Constructor Tool",
  [ECOSYSTEM_TOOLS]: "Major Universal Constructors for Ecosystem Mapping",
  [INTERACTIVE_MINDMAP_ECO]: "Interactive Landscape Mindmaps",
  [STATS_MACRO]: "Statistical Macroparametrs",
};

// replace with ReactNode and remove lazy loading
export const COMPONENTS = {
  [NUM13]: "IframeHorizontalBarStacked",
  [COMPARISON_BARS]: "ComparisonBars",
  [ARROW_PROGRESS_CHART]: "ArrowProgressChart",
  [PYRAMID]: "PyramidDesignerV2",
  [RADAR_CHART_BLURRED]: "RadarChartBlurred",
};

export const getName = (diagramName = "") => {
  return NAMES[diagramName] || diagramName;
};
