export const geoDashboardThemeData = [
    {
        itemName: "Default",
        className: "",
        id: 1,
        isActive: true,
        name: "default",
        backgroundHeader: "linear-gradient(-30deg, #398bbc 0%, #0c5393 40%, #398bbc 50%)",
        backgroundFooter: "linear-gradient(90deg, #0c5393 0%, #398bbc 100%)",
        textColor: "black",
        barColor1: "#0c5393",
        barColor2: "#398bbc",
        radarSettings: {
            backgroundColor: "rgba(54, 162, 235, 0.2)",
            borderColor: "#398bbc",
            pointBackgroundColor: "#398bbc",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#398bbc"
        }
    },
    {
        itemName: "Agrifood and Organic Agriculture",
        className: "",
        id: 2,
        isActive: false,
        name: "agrifood",
        backgroundHeader: "linear-gradient(-30deg, #e85064 0%, #17af9b 40%, #e85064 50%)",
        backgroundFooter: "linear-gradient(90deg, #17af9b 0%, #e85064 100%)",
        textColor: "white",
        barColor1: "#17af9b",
        barColor2: "#e85064",
        radarSettings: {
            backgroundColor: "rgba(23, 175, 155, 0.2)",
            borderColor: "#17af9b",
            pointBackgroundColor: "#17af9b",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#17af9b"
        },
    },
    {
        itemName: "Organic Agriculture",
        className: "",
        id: 3,
        isActive: false,
        name: "Organic Agriculture",
        backgroundHeader: "linear-gradient(-30deg, #f9b700 0%, #0648ff 40%, #f9b700 50%)",
        backgroundFooter: "linear-gradient(90deg, #0648ff 0%, #f9b700 100%)",
        textColor: "white",
        barColor1: "#0648ff",
        barColor2: "#f9b700",
        radarSettings: {
            backgroundColor: "rgba(249, 183, 0, 0.2)",
            borderColor: "#f9b700",
            pointBackgroundColor: "#f9b700",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#f9b700"
        },
    },
    {
        itemName: "Automotive",
        className: "",
        id: 4,
        isActive: false,
        name: "Automotive",
        backgroundHeader: "linear-gradient(-30deg, #8169d6 0%, #7e9629 40%, #8169d6 50%)",
        backgroundFooter: "linear-gradient(90deg, #7e9629 0%, #8169d6 100%)",
        textColor: "white",
        barColor1: "#7e9629",
        barColor2: "#8169d6",
        radarSettings: {
            backgroundColor: "rgba(129, 105, 214, 0.2)",
            borderColor: "#8169d6",
            pointBackgroundColor: "#8169d6",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#8169d6"
        },
    },
    {
        itemName: "Electronics",
        className: "",
        id: 5,
        isActive: false,
        name: "Electronics",
        backgroundHeader: "linear-gradient(-30deg, #15988a 0%, #ea6775 40%, #15988a 50%)",
        backgroundFooter: "linear-gradient(90deg, #ea6775 0%, #15988a 100%)",
        textColor: "white",
        barColor1: "#ea6775",
        barColor2: "#15988a",
        radarSettings: {
            backgroundColor: "rgba(21, 152, 138, 0.2)",
            borderColor: "#15988a",
            pointBackgroundColor: "#15988a",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#15988a"
        },
    },
    {
        itemName: "TAFL",
        className: "",
        id: 6,
        isActive: false,
        name: "TAFL",
        backgroundHeader: "linear-gradient(-30deg, #cd4e86 0%, #32b179 40%, #cd4e86 50%)",
        backgroundFooter: "linear-gradient(90deg, #32b179 0%, #cd4e86 100%)",
        textColor: "white",
        barColor1: "#32b179",
        barColor2: "#cd4e86",
        radarSettings: {
            backgroundColor: "rgba(205, 78, 134, 0.2)",
            borderColor: "#cd4e86",
            pointBackgroundColor: "#cd4e86",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#cd4e86"
        },
    },
    {
        itemName: "ICT",
        className: "",
        id: 7,
        isActive: false,
        name: "ICT",
        backgroundHeader: "linear-gradient(-30deg, #19a7e0 0%, #e6581f 40%, #19a7e0 50%)",
        backgroundFooter: "linear-gradient(90deg, #e6581f 0%, #19a7e0 100%)",
        textColor: "white",
        barColor1: "#e6581f",
        barColor2: "#19a7e0",
        radarSettings: {
            backgroundColor: "rgba(25, 167, 224, 0.2)",
            borderColor: "#19a7e0",
            pointBackgroundColor: "#19a7e0",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#19a7e0"
        },
    },
    {
        itemName: "Renewable Energy",
        className: "",
        id: 8,
        isActive: false,
        name: "Renewable Energy",
        backgroundHeader: "linear-gradient(-30deg, #23b95e 0%, #dc46a1 40%, #23b95e 50%)",
        backgroundFooter: "linear-gradient(90deg, #dc46a1 0%, #23b95e 100%)",
        textColor: "white",
        barColor1: "#dc46a1",
        barColor2: "#23b95e",
        radarSettings: {
            backgroundColor: "rgba(235, 185, 94, 0.2)",
            borderColor: "#23b95e",
            pointBackgroundColor: "#23b95e",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#23b95e"
        },
    },
    {
        itemName: "BPO&SSC",
        className: "",
        id: 9,
        isActive: false,
        name: "BPO&SSC",
        backgroundHeader: "linear-gradient(-30deg, #437ec1 0%, #bc813e 40%, #437ec1 50%)",
        backgroundFooter: "linear-gradient(90deg, #bc813e 0%, #437ec1 100%)",
        textColor: "white",
        barColor1: "#bc813e",
        barColor2: "#437ec1",
        radarSettings: {
            backgroundColor: "rgba(67, 126, 193, 0.2)",
            borderColor: "#437ec1",
            pointBackgroundColor: "#437ec1",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#437ec1"
        },
    },
    {
        itemName: "Creative industries",
        className: "",
        id: 10,
        isActive: false,
        name: "Creative industries",
        backgroundHeader: "linear-gradient(-30deg, #cd4e86 0%, #32b179 40%, #cd4e86 50%)",
        backgroundFooter: "linear-gradient(90deg, #32b179 0%, #cd4e86 100%)",
        textColor: "white",
        barColor1: "#32b179",
        barColor2: "#cd4e86",
        radarSettings: {
            backgroundColor: "rgba(205, 78, 134, 0.2)",
            borderColor: "#cd4e86",
            pointBackgroundColor: "#cd4e86",
            pointBorderColor: "#fff",
            pointHoverBackgroundColor: "#fff",
            pointHoverBorderColor: "#cd4e86"
        },
    }
  ];
