export const originalData = {
    name: 'Australia: #8 Region',
    country: 'Australia',
    score: 716,
    data: [
        {
            title: 'COVID-19 Regional Resiliency',
            weight: 1.3,
            score: 0.687,
            points: 89,
            items: [
                'Infection Spread Risk',
                'Culture Specifics and Societal Discipline',
                'Level of Modern Sanitization Methods',
                'Demography',
                'Chronic Diseases',
                'Societal Risks',
            ],
            factors: [0.0909, 0.1161, 0.15, 0.0689, 0.0751, 0.136],
        },
        {
            title: 'COVID-19 Emergency Preparedness',
            weight: 1.5,
            score: 0.7883,
            points: 118,
            items: [
                'Social Emergency Resilience',
                'Emergency Military Mobilization Experience',
                'Surveillance Capabilities (Scale, Scope and Technological Sophistication)',
                'Previous National Emergency Experience',
            ],
            factors: [0.2025, 0.1533, 0.2025, 0.23],
        },
        {
            title: 'COVID-19 Monitoring and Detection',
            weight: 1.5,
            score: 0.7703,
            points: 116,
            items: [
                'Monitoring Systems and Disaster Management',
                'Scope of Diagnosic Methods',
                'Testing Efficiency',
                'AI for Diagnostics and Prognostics',
                'Government Surveillance Technology for Monitoring',
                'Reliability and Transparency of Data',
            ],
            factors: [0.18, 0.15, 0.092, 0.15, 0.85, 0.1133],
        },
        {
            title: 'COVID-19 Government Efficiency of Risk Management',
            weight: 2.2,
            score: 0.8221,
            points: 181,
            items: [
                'Level of Security and Defense Advancement',
                'Rapid Emergency Mobilization',
                'Efficiency of Government Structure',
                'Economic Sustainability',
                'Legislative Efficiency',
                'Political Stability',
            ],
            factors: [0.17, 0.1543, 0.145, 0.0785, 0.12, 0.1543],
        },
        {
            title: 'COVID-19 Quarantine Efficiency',
            weight: 2.2,
            score: 0.5959,
            points: 131,
            items: [
                'Scale of Quarantine',
                'Quarantine Timeline',
                'Criminal Penalties for Violating Quarantine',
                'Economic Support for quarantined Citizens',
                'Economic and Supply Chain Freezing',
                'Travel Restrictions',
            ],
            factors: [0.1651, 0.0567, 0.0759, 0.072, 0.124, 0.1021],
        },
        {
            title: 'COVID-19 Healthcare Readiness',
            weight: 1.3,
            score: 0.6218,
            points: 81,
            items: [
                'COVID-19 Equipment Availability',
                'Mobilization of New Healthcare Resources',
                'Quantity and Quality of Medical Staff',
                'Level of Healthcare Progressiveness',
                'Level of Technological Advancement',
                'Epidemiology System Level of Development',
            ],
            factors: [0.1047, 0.1458, 0.1341, 0.0929, 0.0196, 0.1246],
        },
    ],
};
