export const mockData = {
  originalData: {
    title: "Digital Map of Switzerland",
    backgroundColor: "transparent",
    fontColor: "black",
    hoverColor: "#3b729f",
    markers: [],
    colors: {
      Valais: "",
      Ticino: "",
      Graubünden: "",
      Schaffhausen: "",
      Thurgau: "",
      Zürich: "",
      Aargau: "",
      "Basel-Stadt": "",
      "Basel-Landschaft": "",
      "Sankt Gallen": "",
      Solothurn: "",
      Jura: "",
      Genève: "",
      Vaud: "",
      Neuchâtel: "",
      Bern: "",
      Lucerne: "",
      Zug: "",
      Uri: "",
      Schwyz: "",
      Glarus: "",
      Nidwalden: "",
      Fribourg: "",
      Obwalden: "",
      "Appenzell Ausserrhoden": "",
      "Appenzell Innerrhoden": "",
    },
  },
};
