# Generated by Django 4.2 on 2023-12-19 13:29

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models
import django.db.models.deletion


def populate_user_profile(apps, schema_editor):
    User = get_user_model()
    UserProfile = apps.get_model("core", "UserProfile")
    for u in User.objects.all().iterator():
        UserProfile.objects.create(
            user_id=u.id,
            is_editor=True,
        )


def delete_user_profile(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")
    UserProfile.objects.delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_editor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            populate_user_profile,
            delete_user_profile,
        )
    ]
