# Generated by Django 4.2 on 2024-01-18 08:58

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='source',
            field=models.FileField(storage=core.storage.AzureStaticStorage, upload_to='files/'),
        ),
    ]
